import type { EarnVault } from "@/types/earn";

export const MOCK_IDLE_BALANCE = 428.16;

export const FALLBACK_VAULTS: EarnVault[] = [
  {
    vaultName: "RE7USDC",
    slug: "8453-re7usdc",
    protocol: "morpho-v1",
    protocolLabel: "Morpho",
    protocolUrl: "https://app.morpho.org/base",
    chain: "Base",
    chainId: 8453,
    asset: "USDC",
    apy: 5.77,
    baseApy: 5.77,
    rewardApy: 0,
    tvlUsd: 2048964,
    summary: "A calm USDC home on Base with instant deposit support and a recognizable protocol surface.",
    description: "Stablecoin vault on Base",
    tags: ["stablecoin", "single"],
    hasInstantDeposit: true,
    isStablecoinLike: true,
    isTransactional: true,
    isRedeemable: true,
  },
  {
    vaultName: "CSUSDC",
    slug: "8453-csusdc",
    protocol: "morpho-v1",
    protocolLabel: "Morpho",
    protocolUrl: "https://app.morpho.org/base",
    chain: "Base",
    chainId: 8453,
    asset: "USDC",
    apy: 5.27,
    baseApy: 5.27,
    rewardApy: 0,
    tvlUsd: 4445868,
    summary: "Another stable USDC route on Base with a simple deposit story and solid liquidity.",
    description: "Stablecoin vault on Base",
    tags: ["stablecoin", "single"],
    hasInstantDeposit: true,
    isStablecoinLike: true,
    isTransactional: true,
    isRedeemable: true,
  },
  {
    vaultName: "Aave USDC",
    slug: "42161-aave-usdc",
    protocol: "aave-v3",
    protocolLabel: "Aave",
    protocolUrl: "https://app.aave.com/",
    chain: "Arbitrum",
    chainId: 42161,
    asset: "USDC",
    apy: 4.12,
    baseApy: 4.12,
    rewardApy: 0,
    tvlUsd: 8500000,
    summary: "A familiar stablecoin route for a conservative deposit-and-chill flow.",
    description: "Stablecoin market on Arbitrum",
    tags: ["stablecoin", "single"],
    hasInstantDeposit: true,
    isStablecoinLike: true,
    isTransactional: true,
    isRedeemable: true,
  },
];
